/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChainTypeEnum = {
    Xym: 'XYM',
    Eth: 'ETH'
} as const;
export type ChainTypeEnum = typeof ChainTypeEnum[keyof typeof ChainTypeEnum];


export function ChainTypeEnumFromJSON(json: any): ChainTypeEnum {
    return ChainTypeEnumFromJSONTyped(json, false);
}

export function ChainTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainTypeEnum {
    return json as ChainTypeEnum;
}

export function ChainTypeEnumToJSON(value?: ChainTypeEnum | null): any {
    return value as any;
}

