/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostQuestApprovalResponse
 */
export interface PostQuestApprovalResponse {
    /**
     * serialized aggregate complete transaction
     * @type {string}
     * @memberof PostQuestApprovalResponse
     */
    transaction: string;
}

/**
 * Check if a given object implements the PostQuestApprovalResponse interface.
 */
export function instanceOfPostQuestApprovalResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transaction" in value;

    return isInstance;
}

export function PostQuestApprovalResponseFromJSON(json: any): PostQuestApprovalResponse {
    return PostQuestApprovalResponseFromJSONTyped(json, false);
}

export function PostQuestApprovalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostQuestApprovalResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transaction': json['transaction'],
    };
}

export function PostQuestApprovalResponseToJSON(value?: PostQuestApprovalResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transaction': value.transaction,
    };
}

