/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserProfileImageRequest
 */
export interface UpdateUserProfileImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UpdateUserProfileImageRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the UpdateUserProfileImageRequest interface.
 */
export function instanceOfUpdateUserProfileImageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function UpdateUserProfileImageRequestFromJSON(json: any): UpdateUserProfileImageRequest {
    return UpdateUserProfileImageRequestFromJSONTyped(json, false);
}

export function UpdateUserProfileImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserProfileImageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function UpdateUserProfileImageRequestToJSON(value?: UpdateUserProfileImageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

