/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountNamesDTO } from './AccountNamesDTO';
import {
    AccountNamesDTOFromJSON,
    AccountNamesDTOFromJSONTyped,
    AccountNamesDTOToJSON,
} from './AccountNamesDTO';

/**
 * 
 * @export
 * @interface AccountsNamesDTO
 */
export interface AccountsNamesDTO {
    /**
     * Array of account names.
     * @type {Array<AccountNamesDTO>}
     * @memberof AccountsNamesDTO
     */
    accountNames: Array<AccountNamesDTO>;
}

/**
 * Check if a given object implements the AccountsNamesDTO interface.
 */
export function instanceOfAccountsNamesDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountNames" in value;

    return isInstance;
}

export function AccountsNamesDTOFromJSON(json: any): AccountsNamesDTO {
    return AccountsNamesDTOFromJSONTyped(json, false);
}

export function AccountsNamesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsNamesDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountNames': ((json['accountNames'] as Array<any>).map(AccountNamesDTOFromJSON)),
    };
}

export function AccountsNamesDTOToJSON(value?: AccountsNamesDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountNames': ((value.accountNames as Array<any>).map(AccountNamesDTOToJSON)),
    };
}

