/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BmTreeSignature } from './BmTreeSignature';
import {
    BmTreeSignatureFromJSON,
    BmTreeSignatureFromJSONTyped,
    BmTreeSignatureToJSON,
} from './BmTreeSignature';
import type { StageEnum } from './StageEnum';
import {
    StageEnumFromJSON,
    StageEnumFromJSONTyped,
    StageEnumToJSON,
} from './StageEnum';

/**
 * 
 * @export
 * @interface MessageGroup
 */
export interface MessageGroup {
    /**
     * 
     * @type {StageEnum}
     * @memberof MessageGroup
     */
    stage: StageEnum;
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof MessageGroup
     */
    height: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageGroup
     */
    hashes: Array<string>;
    /**
     * 
     * @type {Array<BmTreeSignature>}
     * @memberof MessageGroup
     */
    signatures: Array<BmTreeSignature>;
}

/**
 * Check if a given object implements the MessageGroup interface.
 */
export function instanceOfMessageGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stage" in value;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "hashes" in value;
    isInstance = isInstance && "signatures" in value;

    return isInstance;
}

export function MessageGroupFromJSON(json: any): MessageGroup {
    return MessageGroupFromJSONTyped(json, false);
}

export function MessageGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stage': StageEnumFromJSON(json['stage']),
        'height': json['height'],
        'hashes': json['hashes'],
        'signatures': ((json['signatures'] as Array<any>).map(BmTreeSignatureFromJSON)),
    };
}

export function MessageGroupToJSON(value?: MessageGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stage': StageEnumToJSON(value.stage),
        'height': value.height,
        'hashes': value.hashes,
        'signatures': ((value.signatures as Array<any>).map(BmTreeSignatureToJSON)),
    };
}

