/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MosaicGlobalRestrictionEntryRestrictionDTO } from './MosaicGlobalRestrictionEntryRestrictionDTO';
import {
    MosaicGlobalRestrictionEntryRestrictionDTOFromJSON,
    MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped,
    MosaicGlobalRestrictionEntryRestrictionDTOToJSON,
} from './MosaicGlobalRestrictionEntryRestrictionDTO';

/**
 * 
 * @export
 * @interface MosaicGlobalRestrictionEntryDTO
 */
export interface MosaicGlobalRestrictionEntryDTO {
    /**
     * Restriction key.
     * @type {string}
     * @memberof MosaicGlobalRestrictionEntryDTO
     */
    key: string;
    /**
     * 
     * @type {MosaicGlobalRestrictionEntryRestrictionDTO}
     * @memberof MosaicGlobalRestrictionEntryDTO
     */
    restriction: MosaicGlobalRestrictionEntryRestrictionDTO;
}

/**
 * Check if a given object implements the MosaicGlobalRestrictionEntryDTO interface.
 */
export function instanceOfMosaicGlobalRestrictionEntryDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "restriction" in value;

    return isInstance;
}

export function MosaicGlobalRestrictionEntryDTOFromJSON(json: any): MosaicGlobalRestrictionEntryDTO {
    return MosaicGlobalRestrictionEntryDTOFromJSONTyped(json, false);
}

export function MosaicGlobalRestrictionEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicGlobalRestrictionEntryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'restriction': MosaicGlobalRestrictionEntryRestrictionDTOFromJSON(json['restriction']),
    };
}

export function MosaicGlobalRestrictionEntryDTOToJSON(value?: MosaicGlobalRestrictionEntryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'restriction': MosaicGlobalRestrictionEntryRestrictionDTOToJSON(value.restriction),
    };
}

