/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeStatusEnum } from './NodeStatusEnum';
import {
    NodeStatusEnumFromJSON,
    NodeStatusEnumFromJSONTyped,
    NodeStatusEnumToJSON,
} from './NodeStatusEnum';

/**
 * 
 * @export
 * @interface NodeHealthDTO
 */
export interface NodeHealthDTO {
    /**
     * 
     * @type {NodeStatusEnum}
     * @memberof NodeHealthDTO
     */
    apiNode: NodeStatusEnum;
    /**
     * 
     * @type {NodeStatusEnum}
     * @memberof NodeHealthDTO
     */
    db: NodeStatusEnum;
}

/**
 * Check if a given object implements the NodeHealthDTO interface.
 */
export function instanceOfNodeHealthDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "apiNode" in value;
    isInstance = isInstance && "db" in value;

    return isInstance;
}

export function NodeHealthDTOFromJSON(json: any): NodeHealthDTO {
    return NodeHealthDTOFromJSONTyped(json, false);
}

export function NodeHealthDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeHealthDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiNode': NodeStatusEnumFromJSON(json['apiNode']),
        'db': NodeStatusEnumFromJSON(json['db']),
    };
}

export function NodeHealthDTOToJSON(value?: NodeHealthDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiNode': NodeStatusEnumToJSON(value.apiNode),
        'db': NodeStatusEnumToJSON(value.db),
    };
}

