/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountRestrictionsDTOFromJSON, AccountRestrictionsDTOToJSON, } from './AccountRestrictionsDTO';
/**
 * Check if a given object implements the AccountRestrictionsInfoDTO interface.
 */
export function instanceOfAccountRestrictionsInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'accountRestrictions' in value;
    return isInstance;
}
export function AccountRestrictionsInfoDTOFromJSON(json) {
    return AccountRestrictionsInfoDTOFromJSONTyped(json, false);
}
export function AccountRestrictionsInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        accountRestrictions: AccountRestrictionsDTOFromJSON(json['accountRestrictions']),
    };
}
export function AccountRestrictionsInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        accountRestrictions: AccountRestrictionsDTOToJSON(value.accountRestrictions),
    };
}
