/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccountRestrictionFlagsEnum } from './AccountRestrictionFlagsEnum';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
/**
 *
 * @export
 * @interface AccountOperationRestrictionTransactionBodyDTO
 */
export interface AccountOperationRestrictionTransactionBodyDTO {
    /**
     *
     * @type {AccountRestrictionFlagsEnum}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionFlags: AccountRestrictionFlagsEnum;
    /**
     * Account restriction additions.
     * @type {Array<TransactionTypeEnum>}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionAdditions?: Array<TransactionTypeEnum>;
    /**
     * Account restriction deletions.
     * @type {Array<TransactionTypeEnum>}
     * @memberof AccountOperationRestrictionTransactionBodyDTO
     */
    restrictionDeletions?: Array<TransactionTypeEnum>;
}
/**
 * Check if a given object implements the AccountOperationRestrictionTransactionBodyDTO interface.
 */
export declare function instanceOfAccountOperationRestrictionTransactionBodyDTO(value: object): boolean;
export declare function AccountOperationRestrictionTransactionBodyDTOFromJSON(json: any): AccountOperationRestrictionTransactionBodyDTO;
export declare function AccountOperationRestrictionTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountOperationRestrictionTransactionBodyDTO;
export declare function AccountOperationRestrictionTransactionBodyDTOToJSON(value?: AccountOperationRestrictionTransactionBodyDTO | null): any;
