/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountRestrictionDTOValuesInnerFromJSON, AccountRestrictionDTOValuesInnerToJSON, } from './AccountRestrictionDTOValuesInner';
import { AccountRestrictionFlagsEnumFromJSON, AccountRestrictionFlagsEnumToJSON, } from './AccountRestrictionFlagsEnum';
/**
 * Check if a given object implements the AccountRestrictionDTO interface.
 */
export function instanceOfAccountRestrictionDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'restrictionFlags' in value;
    isInstance = isInstance && 'values' in value;
    return isInstance;
}
export function AccountRestrictionDTOFromJSON(json) {
    return AccountRestrictionDTOFromJSONTyped(json, false);
}
export function AccountRestrictionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        restrictionFlags: AccountRestrictionFlagsEnumFromJSON(json['restrictionFlags']),
        values: json['values'].map(AccountRestrictionDTOValuesInnerFromJSON),
    };
}
export function AccountRestrictionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        restrictionFlags: AccountRestrictionFlagsEnumToJSON(value.restrictionFlags),
        values: value.values.map(AccountRestrictionDTOValuesInnerToJSON),
    };
}
