/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Type of account restriction:
 * * 0x0001 (1 decimal) - Allow only incoming transactions from a given address.
 * * 0x0002 (2 decimal) - Allow only incoming transactions containing a given mosaic identifier.
 * * 0x4001 (16385 decimal) - Allow only outgoing transactions to a given address.
 * * 0x4004 (16388 decimal) - Allow only outgoing transactions with a given transaction type.
 * * 0x8001 (32769 decimal) - Block incoming transactions from a given address.
 * * 0x8002 (32770 decimal) - Block incoming transactions containing a given mosaic identifier.
 * * 0xC001 (49153 decimal) - Block outgoing transactions to a given address.
 * * 0xC004 (49156 decimal) - Block outgoing transactions with a given transaction type.
 * @export
 */
export declare const AccountRestrictionFlagsEnum: {
    readonly NUMBER_1: 1;
    readonly NUMBER_2: 2;
    readonly NUMBER_16385: 16385;
    readonly NUMBER_16388: 16388;
    readonly NUMBER_32769: 32769;
    readonly NUMBER_32770: 32770;
    readonly NUMBER_49153: 49153;
    readonly NUMBER_49156: 49156;
};
export type AccountRestrictionFlagsEnum = (typeof AccountRestrictionFlagsEnum)[keyof typeof AccountRestrictionFlagsEnum];
export declare function AccountRestrictionFlagsEnumFromJSON(json: any): AccountRestrictionFlagsEnum;
export declare function AccountRestrictionFlagsEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRestrictionFlagsEnum;
export declare function AccountRestrictionFlagsEnumToJSON(value?: AccountRestrictionFlagsEnum | null): any;
