/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export var AccountOrderByEnum = {
    Id: 'id',
    Balance: 'balance',
};
export function AccountOrderByEnumFromJSON(json) {
    return AccountOrderByEnumFromJSONTyped(json, false);
}
export function AccountOrderByEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function AccountOrderByEnumToJSON(value) {
    return value;
}
