/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CosignatureDTO } from './CosignatureDTO';
/**
 *
 * @export
 * @interface AggregateTransactionBodyDTO
 */
export interface AggregateTransactionBodyDTO {
    /**
     *
     * @type {string}
     * @memberof AggregateTransactionBodyDTO
     */
    transactionsHash: string;
    /**
     * Array of transaction cosignatures.
     * @type {Array<CosignatureDTO>}
     * @memberof AggregateTransactionBodyDTO
     */
    cosignatures: Array<CosignatureDTO>;
}
/**
 * Check if a given object implements the AggregateTransactionBodyDTO interface.
 */
export declare function instanceOfAggregateTransactionBodyDTO(value: object): boolean;
export declare function AggregateTransactionBodyDTOFromJSON(json: any): AggregateTransactionBodyDTO;
export declare function AggregateTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateTransactionBodyDTO;
export declare function AggregateTransactionBodyDTOToJSON(value?: AggregateTransactionBodyDTO | null): any;
