/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CosignatureDTOFromJSON, CosignatureDTOToJSON } from './CosignatureDTO';
/**
 * Check if a given object implements the AggregateTransactionBodyDTO interface.
 */
export function instanceOfAggregateTransactionBodyDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'transactionsHash' in value;
    isInstance = isInstance && 'cosignatures' in value;
    return isInstance;
}
export function AggregateTransactionBodyDTOFromJSON(json) {
    return AggregateTransactionBodyDTOFromJSONTyped(json, false);
}
export function AggregateTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        transactionsHash: json['transactionsHash'],
        cosignatures: json['cosignatures'].map(CosignatureDTOFromJSON),
    };
}
export function AggregateTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        transactionsHash: value.transactionsHash,
        cosignatures: value.cosignatures.map(CosignatureDTOToJSON),
    };
}
