/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Alias action:
 * * 0 - Unlink alias.
 * * 1 - Link alias.
 * @export
 */
export var AliasActionEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
};
export function AliasActionEnumFromJSON(json) {
    return AliasActionEnumFromJSONTyped(json, false);
}
export function AliasActionEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function AliasActionEnumToJSON(value) {
    return value;
}
