/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the AnnounceTransactionInfoDTO interface.
 */
export function instanceOfAnnounceTransactionInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'message' in value;
    return isInstance;
}
export function AnnounceTransactionInfoDTOFromJSON(json) {
    return AnnounceTransactionInfoDTOFromJSONTyped(json, false);
}
export function AnnounceTransactionInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        message: json['message'],
    };
}
export function AnnounceTransactionInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        message: value.message,
    };
}
