/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AnnounceTransactionInfoDTO
 */
export interface AnnounceTransactionInfoDTO {
    /**
     *
     * @type {string}
     * @memberof AnnounceTransactionInfoDTO
     */
    message: string;
}
/**
 * Check if a given object implements the AnnounceTransactionInfoDTO interface.
 */
export declare function instanceOfAnnounceTransactionInfoDTO(value: object): boolean;
export declare function AnnounceTransactionInfoDTOFromJSON(json: any): AnnounceTransactionInfoDTO;
export declare function AnnounceTransactionInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnounceTransactionInfoDTO;
export declare function AnnounceTransactionInfoDTOToJSON(value?: AnnounceTransactionInfoDTO | null): any;
