/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BalanceChangeReceiptDTOAllOf
 */
export interface BalanceChangeReceiptDTOAllOf {
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof BalanceChangeReceiptDTOAllOf
     */
    mosaicId: string;
    /**
     * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
     * @type {string}
     * @memberof BalanceChangeReceiptDTOAllOf
     */
    amount: string;
    /**
     * Address encoded using a 32-character set.
     * @type {string}
     * @memberof BalanceChangeReceiptDTOAllOf
     */
    targetAddress: string;
}
/**
 * Check if a given object implements the BalanceChangeReceiptDTOAllOf interface.
 */
export declare function instanceOfBalanceChangeReceiptDTOAllOf(value: object): boolean;
export declare function BalanceChangeReceiptDTOAllOfFromJSON(json: any): BalanceChangeReceiptDTOAllOf;
export declare function BalanceChangeReceiptDTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceChangeReceiptDTOAllOf;
export declare function BalanceChangeReceiptDTOAllOfToJSON(value?: BalanceChangeReceiptDTOAllOf | null): any;
