/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the BalanceChangeReceiptDTOAllOf interface.
 */
export function instanceOfBalanceChangeReceiptDTOAllOf(value) {
    var isInstance = true;
    isInstance = isInstance && 'mosaicId' in value;
    isInstance = isInstance && 'amount' in value;
    isInstance = isInstance && 'targetAddress' in value;
    return isInstance;
}
export function BalanceChangeReceiptDTOAllOfFromJSON(json) {
    return BalanceChangeReceiptDTOAllOfFromJSONTyped(json, false);
}
export function BalanceChangeReceiptDTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        mosaicId: json['mosaicId'],
        amount: json['amount'],
        targetAddress: json['targetAddress'],
    };
}
export function BalanceChangeReceiptDTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        mosaicId: value.mosaicId,
        amount: value.amount,
        targetAddress: value.targetAddress,
    };
}
