/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { BlockInfoDTO } from './BlockInfoDTO';
import type { Pagination } from './Pagination';
/**
 *
 * @export
 * @interface BlockPage
 */
export interface BlockPage {
    /**
     * Array of blocks.
     * @type {Array<BlockInfoDTO>}
     * @memberof BlockPage
     */
    data: Array<BlockInfoDTO>;
    /**
     *
     * @type {Pagination}
     * @memberof BlockPage
     */
    pagination: Pagination;
}
/**
 * Check if a given object implements the BlockPage interface.
 */
export declare function instanceOfBlockPage(value: object): boolean;
export declare function BlockPageFromJSON(json: any): BlockPage;
export declare function BlockPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockPage;
export declare function BlockPageToJSON(value?: BlockPage | null): any;
