/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ParentPublicKeySignaturePair } from './ParentPublicKeySignaturePair';
/**
 *
 * @export
 * @interface BmTreeSignature
 */
export interface BmTreeSignature {
    /**
     *
     * @type {ParentPublicKeySignaturePair}
     * @memberof BmTreeSignature
     */
    root: ParentPublicKeySignaturePair;
    /**
     *
     * @type {ParentPublicKeySignaturePair}
     * @memberof BmTreeSignature
     */
    bottom: ParentPublicKeySignaturePair;
}
/**
 * Check if a given object implements the BmTreeSignature interface.
 */
export declare function instanceOfBmTreeSignature(value: object): boolean;
export declare function BmTreeSignatureFromJSON(json: any): BmTreeSignature;
export declare function BmTreeSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): BmTreeSignature;
export declare function BmTreeSignatureToJSON(value?: BmTreeSignature | null): any;
