/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Cosignature
 */
export interface Cosignature {
    /**
     *
     * @type {string}
     * @memberof Cosignature
     */
    parentHash?: string;
    /**
     * Entity's signature generated by the signer.
     * @type {string}
     * @memberof Cosignature
     */
    signature?: string;
    /**
     * Public key.
     * @type {string}
     * @memberof Cosignature
     */
    signerPublicKey?: string;
    /**
     * Cosignature version.
     * @type {string}
     * @memberof Cosignature
     */
    version?: string;
}
/**
 * Check if a given object implements the Cosignature interface.
 */
export declare function instanceOfCosignature(value: object): boolean;
export declare function CosignatureFromJSON(json: any): Cosignature;
export declare function CosignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cosignature;
export declare function CosignatureToJSON(value?: Cosignature | null): any;
