/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { LockHashAlgorithmEnum } from './LockHashAlgorithmEnum';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
/**
 *
 * @export
 * @interface EmbeddedSecretProofTransactionDTO
 */
export interface EmbeddedSecretProofTransactionDTO {
    /**
     * Public key.
     * @type {string}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version.
     * @type {number}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    version: number;
    /**
     *
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     *
     * @type {number}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    type: number;
    /**
     * Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a
     * regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.
     * Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA
     * @type {string}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    recipientAddress: string;
    /**
     *
     * @type {string}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    secret: string;
    /**
     *
     * @type {LockHashAlgorithmEnum}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    hashAlgorithm: LockHashAlgorithmEnum;
    /**
     * Original random set of bytes.
     * @type {string}
     * @memberof EmbeddedSecretProofTransactionDTO
     */
    proof: string;
}
/**
 * Check if a given object implements the EmbeddedSecretProofTransactionDTO interface.
 */
export declare function instanceOfEmbeddedSecretProofTransactionDTO(value: object): boolean;
export declare function EmbeddedSecretProofTransactionDTOFromJSON(json: any): EmbeddedSecretProofTransactionDTO;
export declare function EmbeddedSecretProofTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedSecretProofTransactionDTO;
export declare function EmbeddedSecretProofTransactionDTOToJSON(value?: EmbeddedSecretProofTransactionDTO | null): any;
