/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AliasActionEnum } from './AliasActionEnum';
import type { NetworkTypeEnum } from './NetworkTypeEnum';
/**
 *
 * @export
 * @interface EmbeddedMosaicAliasTransactionDTO
 */
export interface EmbeddedMosaicAliasTransactionDTO {
    /**
     * Public key.
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version.
     * @type {number}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    version: number;
    /**
     *
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     *
     * @type {number}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    type: number;
    /**
     * Namespace identifier.
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    namespaceId: string;
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    mosaicId: string;
    /**
     *
     * @type {AliasActionEnum}
     * @memberof EmbeddedMosaicAliasTransactionDTO
     */
    aliasAction: AliasActionEnum;
}
/**
 * Check if a given object implements the EmbeddedMosaicAliasTransactionDTO interface.
 */
export declare function instanceOfEmbeddedMosaicAliasTransactionDTO(value: object): boolean;
export declare function EmbeddedMosaicAliasTransactionDTOFromJSON(json: any): EmbeddedMosaicAliasTransactionDTO;
export declare function EmbeddedMosaicAliasTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedMosaicAliasTransactionDTO;
export declare function EmbeddedMosaicAliasTransactionDTOToJSON(value?: EmbeddedMosaicAliasTransactionDTO | null): any;
