/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InflationReceiptDTOAllOf
 */
export interface InflationReceiptDTOAllOf {
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof InflationReceiptDTOAllOf
     */
    mosaicId: string;
    /**
     * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
     * @type {string}
     * @memberof InflationReceiptDTOAllOf
     */
    amount: string;
}
/**
 * Check if a given object implements the InflationReceiptDTOAllOf interface.
 */
export declare function instanceOfInflationReceiptDTOAllOf(value: object): boolean;
export declare function InflationReceiptDTOAllOfFromJSON(json: any): InflationReceiptDTOAllOf;
export declare function InflationReceiptDTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InflationReceiptDTOAllOf;
export declare function InflationReceiptDTOAllOfToJSON(value?: InflationReceiptDTOAllOf | null): any;
