/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { MerklePathItemDTOFromJSON, MerklePathItemDTOToJSON, } from './MerklePathItemDTO';
/**
 * Check if a given object implements the MerkleProofInfoDTO interface.
 */
export function instanceOfMerkleProofInfoDTO(value) {
    var isInstance = true;
    return isInstance;
}
export function MerkleProofInfoDTOFromJSON(json) {
    return MerkleProofInfoDTOFromJSONTyped(json, false);
}
export function MerkleProofInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        merklePath: !exists(json, 'merklePath')
            ? undefined
            : json['merklePath'].map(MerklePathItemDTOFromJSON),
    };
}
export function MerkleProofInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        merklePath: value.merklePath === undefined ? undefined : value.merklePath.map(MerklePathItemDTOToJSON),
    };
}
