/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { PositionEnumFromJSON, PositionEnumToJSON } from './PositionEnum';
/**
 * Check if a given object implements the MerklePathItemDTO interface.
 */
export function instanceOfMerklePathItemDTO(value) {
    var isInstance = true;
    return isInstance;
}
export function MerklePathItemDTOFromJSON(json) {
    return MerklePathItemDTOFromJSONTyped(json, false);
}
export function MerklePathItemDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        position: !exists(json, 'position') ? undefined : PositionEnumFromJSON(json['position']),
        hash: !exists(json, 'hash') ? undefined : json['hash'],
    };
}
export function MerklePathItemDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        position: PositionEnumToJSON(value.position),
        hash: value.hash,
    };
}
