/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the MerkleTreeBranchLinkDTO interface.
 */
export function instanceOfMerkleTreeBranchLinkDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'bit' in value;
    isInstance = isInstance && 'link' in value;
    return isInstance;
}
export function MerkleTreeBranchLinkDTOFromJSON(json) {
    return MerkleTreeBranchLinkDTOFromJSONTyped(json, false);
}
export function MerkleTreeBranchLinkDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        bit: json['bit'],
        link: json['link'],
    };
}
export function MerkleTreeBranchLinkDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        bit: value.bit,
        link: value.link,
    };
}
