/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MerklePathItemDTO } from './MerklePathItemDTO';
/**
 *
 * @export
 * @interface MerkleProofInfoDTO
 */
export interface MerkleProofInfoDTO {
    /**
     * List of complementary merkle path items needed to recalculate the merkle root.
     * @type {Array<MerklePathItemDTO>}
     * @memberof MerkleProofInfoDTO
     */
    merklePath?: Array<MerklePathItemDTO>;
}
/**
 * Check if a given object implements the MerkleProofInfoDTO interface.
 */
export declare function instanceOfMerkleProofInfoDTO(value: object): boolean;
export declare function MerkleProofInfoDTOFromJSON(json: any): MerkleProofInfoDTO;
export declare function MerkleProofInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerkleProofInfoDTO;
export declare function MerkleProofInfoDTOToJSON(value?: MerkleProofInfoDTO | null): any;
