/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BmTreeSignatureFromJSON, BmTreeSignatureToJSON } from './BmTreeSignature';
import { StageEnumFromJSON, StageEnumToJSON } from './StageEnum';
/**
 * Check if a given object implements the MessageGroup interface.
 */
export function instanceOfMessageGroup(value) {
    var isInstance = true;
    isInstance = isInstance && 'stage' in value;
    isInstance = isInstance && 'height' in value;
    isInstance = isInstance && 'hashes' in value;
    isInstance = isInstance && 'signatures' in value;
    return isInstance;
}
export function MessageGroupFromJSON(json) {
    return MessageGroupFromJSONTyped(json, false);
}
export function MessageGroupFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        stage: StageEnumFromJSON(json['stage']),
        height: json['height'],
        hashes: json['hashes'],
        signatures: json['signatures'].map(BmTreeSignatureFromJSON),
    };
}
export function MessageGroupToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        stage: StageEnumToJSON(value.stage),
        height: value.height,
        hashes: value.hashes,
        signatures: value.signatures.map(BmTreeSignatureToJSON),
    };
}
