/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the MetadataEntryDTOTargetId interface.
 */
export function instanceOfMetadataEntryDTOTargetId(value) {
    var isInstance = true;
    return isInstance;
}
export function MetadataEntryDTOTargetIdFromJSON(json) {
    return MetadataEntryDTOTargetIdFromJSONTyped(json, false);
}
export function MetadataEntryDTOTargetIdFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function MetadataEntryDTOTargetIdToJSON(value) {
    return value;
}
