/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataInfoDTOFromJSON, MetadataInfoDTOToJSON } from './MetadataInfoDTO';
import { PaginationFromJSON, PaginationToJSON } from './Pagination';
/**
 * Check if a given object implements the MetadataPage interface.
 */
export function instanceOfMetadataPage(value) {
    var isInstance = true;
    isInstance = isInstance && 'data' in value;
    isInstance = isInstance && 'pagination' in value;
    return isInstance;
}
export function MetadataPageFromJSON(json) {
    return MetadataPageFromJSONTyped(json, false);
}
export function MetadataPageFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        data: json['data'].map(MetadataInfoDTOFromJSON),
        pagination: PaginationFromJSON(json['pagination']),
    };
}
export function MetadataPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        data: value.data.map(MetadataInfoDTOToJSON),
        pagination: PaginationToJSON(value.pagination),
    };
}
