/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataEntryDTOFromJSON, MetadataEntryDTOToJSON } from './MetadataEntryDTO';
/**
 * Check if a given object implements the MetadataInfoDTO interface.
 */
export function instanceOfMetadataInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'metadataEntry' in value;
    return isInstance;
}
export function MetadataInfoDTOFromJSON(json) {
    return MetadataInfoDTOFromJSONTyped(json, false);
}
export function MetadataInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        metadataEntry: MetadataEntryDTOFromJSON(json['metadataEntry']),
    };
}
export function MetadataInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        metadataEntry: MetadataEntryDTOToJSON(value.metadataEntry),
    };
}
