/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value) {
    var isInstance = true;
    isInstance = isInstance && 'code' in value;
    isInstance = isInstance && 'message' in value;
    return isInstance;
}
export function ModelErrorFromJSON(json) {
    return ModelErrorFromJSONTyped(json, false);
}
export function ModelErrorFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        code: json['code'],
        message: json['message'],
    };
}
export function ModelErrorToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        code: value.code,
        message: value.message,
    };
}
