/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface MosaicExpiryReceiptDTOAllOf
 */
export interface MosaicExpiryReceiptDTOAllOf {
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof MosaicExpiryReceiptDTOAllOf
     */
    artifactId: string;
}
/**
 * Check if a given object implements the MosaicExpiryReceiptDTOAllOf interface.
 */
export declare function instanceOfMosaicExpiryReceiptDTOAllOf(value: object): boolean;
export declare function MosaicExpiryReceiptDTOAllOfFromJSON(json: any): MosaicExpiryReceiptDTOAllOf;
export declare function MosaicExpiryReceiptDTOAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicExpiryReceiptDTOAllOf;
export declare function MosaicExpiryReceiptDTOAllOfToJSON(value?: MosaicExpiryReceiptDTOAllOf | null): any;
