/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the MosaicNamesDTO interface.
 */
export function instanceOfMosaicNamesDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'mosaicId' in value;
    isInstance = isInstance && 'names' in value;
    return isInstance;
}
export function MosaicNamesDTOFromJSON(json) {
    return MosaicNamesDTOFromJSONTyped(json, false);
}
export function MosaicNamesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        mosaicId: json['mosaicId'],
        names: json['names'],
    };
}
export function MosaicNamesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        mosaicId: value.mosaicId,
        names: value.names,
    };
}
