/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MosaicDTOFromJSON, MosaicDTOToJSON } from './MosaicDTO';
/**
 * Check if a given object implements the MosaicInfoDTO interface.
 */
export function instanceOfMosaicInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'mosaic' in value;
    return isInstance;
}
export function MosaicInfoDTOFromJSON(json) {
    return MosaicInfoDTOFromJSONTyped(json, false);
}
export function MosaicInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        mosaic: MosaicDTOFromJSON(json['mosaic']),
    };
}
export function MosaicInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        mosaic: MosaicDTOToJSON(value.mosaic),
    };
}
