/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MosaicAddressRestrictionEntryDTO } from './MosaicAddressRestrictionEntryDTO';
import type { MosaicRestrictionEntryTypeEnum } from './MosaicRestrictionEntryTypeEnum';
/**
 *
 * @export
 * @interface MosaicAddressRestrictionEntryWrapperDTO
 */
export interface MosaicAddressRestrictionEntryWrapperDTO {
    /**
     * The version of the state
     * @type {number}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    compositeHash: string;
    /**
     *
     * @type {MosaicRestrictionEntryTypeEnum}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    entryType: MosaicRestrictionEntryTypeEnum;
    /**
     * Mosaic identifier.
     * @type {string}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    mosaicId: string;
    /**
     * Address encoded using a 32-character set.
     * @type {string}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    targetAddress: string;
    /**
     *
     * @type {Array<MosaicAddressRestrictionEntryDTO>}
     * @memberof MosaicAddressRestrictionEntryWrapperDTO
     */
    restrictions: Array<MosaicAddressRestrictionEntryDTO>;
}
/**
 * Check if a given object implements the MosaicAddressRestrictionEntryWrapperDTO interface.
 */
export declare function instanceOfMosaicAddressRestrictionEntryWrapperDTO(value: object): boolean;
export declare function MosaicAddressRestrictionEntryWrapperDTOFromJSON(json: any): MosaicAddressRestrictionEntryWrapperDTO;
export declare function MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicAddressRestrictionEntryWrapperDTO;
export declare function MosaicAddressRestrictionEntryWrapperDTOToJSON(value?: MosaicAddressRestrictionEntryWrapperDTO | null): any;
