/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the MosaicDefinitionTransactionBodyDTO interface.
 */
export function instanceOfMosaicDefinitionTransactionBodyDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'id' in value;
    isInstance = isInstance && 'duration' in value;
    isInstance = isInstance && 'nonce' in value;
    isInstance = isInstance && 'flags' in value;
    isInstance = isInstance && 'divisibility' in value;
    return isInstance;
}
export function MosaicDefinitionTransactionBodyDTOFromJSON(json) {
    return MosaicDefinitionTransactionBodyDTOFromJSONTyped(json, false);
}
export function MosaicDefinitionTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json['id'],
        duration: json['duration'],
        nonce: json['nonce'],
        flags: json['flags'],
        divisibility: json['divisibility'],
    };
}
export function MosaicDefinitionTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        duration: value.duration,
        nonce: value.nonce,
        flags: value.flags,
        divisibility: value.divisibility,
    };
}
