/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MosaicSupplyChangeActionEnumFromJSON, MosaicSupplyChangeActionEnumToJSON, } from './MosaicSupplyChangeActionEnum';
/**
 * Check if a given object implements the MosaicSupplyChangeTransactionBodyDTO interface.
 */
export function instanceOfMosaicSupplyChangeTransactionBodyDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'mosaicId' in value;
    isInstance = isInstance && 'delta' in value;
    isInstance = isInstance && 'action' in value;
    return isInstance;
}
export function MosaicSupplyChangeTransactionBodyDTOFromJSON(json) {
    return MosaicSupplyChangeTransactionBodyDTOFromJSONTyped(json, false);
}
export function MosaicSupplyChangeTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        mosaicId: json['mosaicId'],
        delta: json['delta'],
        action: MosaicSupplyChangeActionEnumFromJSON(json['action']),
    };
}
export function MosaicSupplyChangeTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        mosaicId: value.mosaicId,
        delta: value.delta,
        action: MosaicSupplyChangeActionEnumToJSON(value.action),
    };
}
