/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MosaicRestrictionsPageDataInner } from './MosaicRestrictionsPageDataInner';
import type { Pagination } from './Pagination';
/**
 *
 * @export
 * @interface MosaicRestrictionsPage
 */
export interface MosaicRestrictionsPage {
    /**
     * Array of mosaic restrictions.
     * @type {Array<MosaicRestrictionsPageDataInner>}
     * @memberof MosaicRestrictionsPage
     */
    data: Array<MosaicRestrictionsPageDataInner>;
    /**
     *
     * @type {Pagination}
     * @memberof MosaicRestrictionsPage
     */
    pagination: Pagination;
}
/**
 * Check if a given object implements the MosaicRestrictionsPage interface.
 */
export declare function instanceOfMosaicRestrictionsPage(value: object): boolean;
export declare function MosaicRestrictionsPageFromJSON(json: any): MosaicRestrictionsPage;
export declare function MosaicRestrictionsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicRestrictionsPage;
export declare function MosaicRestrictionsPageToJSON(value?: MosaicRestrictionsPage | null): any;
