/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the MosaicRestrictionNetworkPropertiesDTO interface.
 */
export function instanceOfMosaicRestrictionNetworkPropertiesDTO(value) {
    var isInstance = true;
    return isInstance;
}
export function MosaicRestrictionNetworkPropertiesDTOFromJSON(json) {
    return MosaicRestrictionNetworkPropertiesDTOFromJSONTyped(json, false);
}
export function MosaicRestrictionNetworkPropertiesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        maxMosaicRestrictionValues: !exists(json, 'maxMosaicRestrictionValues')
            ? undefined
            : json['maxMosaicRestrictionValues'],
    };
}
export function MosaicRestrictionNetworkPropertiesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        maxMosaicRestrictionValues: value.maxMosaicRestrictionValues,
    };
}
