/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MultisigAccountInfoDTO } from './MultisigAccountInfoDTO';
/**
 *
 * @export
 * @interface MultisigAccountGraphInfoDTO
 */
export interface MultisigAccountGraphInfoDTO {
    /**
     * Level of the multisig account.
     * @type {number}
     * @memberof MultisigAccountGraphInfoDTO
     */
    level: number;
    /**
     * Array of multisig accounts for this level.
     * @type {Array<MultisigAccountInfoDTO>}
     * @memberof MultisigAccountGraphInfoDTO
     */
    multisigEntries: Array<MultisigAccountInfoDTO>;
}
/**
 * Check if a given object implements the MultisigAccountGraphInfoDTO interface.
 */
export declare function instanceOfMultisigAccountGraphInfoDTO(value: object): boolean;
export declare function MultisigAccountGraphInfoDTOFromJSON(json: any): MultisigAccountGraphInfoDTO;
export declare function MultisigAccountGraphInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultisigAccountGraphInfoDTO;
export declare function MultisigAccountGraphInfoDTOToJSON(value?: MultisigAccountGraphInfoDTO | null): any;
