/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface NamespaceIds
 */
export interface NamespaceIds {
    /**
     * Array of namespace identifiers.
     * @type {Array<string>}
     * @memberof NamespaceIds
     */
    namespaceIds?: Array<string>;
}
/**
 * Check if a given object implements the NamespaceIds interface.
 */
export declare function instanceOfNamespaceIds(value: object): boolean;
export declare function NamespaceIdsFromJSON(json: any): NamespaceIds;
export declare function NamespaceIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceIds;
export declare function NamespaceIdsToJSON(value?: NamespaceIds | null): any;
