/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { NodeIdentityEqualityStrategy } from './NodeIdentityEqualityStrategy';
/**
 * Network related configuration properties.
 * @export
 * @interface NetworkPropertiesDTO
 */
export interface NetworkPropertiesDTO {
    /**
     * Network identifier.
     * @type {string}
     * @memberof NetworkPropertiesDTO
     */
    identifier?: string;
    /**
     *
     * @type {NodeIdentityEqualityStrategy}
     * @memberof NetworkPropertiesDTO
     */
    nodeEqualityStrategy?: NodeIdentityEqualityStrategy;
    /**
     * Public key.
     * @type {string}
     * @memberof NetworkPropertiesDTO
     */
    nemesisSignerPublicKey?: string;
    /**
     *
     * @type {string}
     * @memberof NetworkPropertiesDTO
     */
    generationHashSeed?: string;
    /**
     * Nemesis epoch time adjustment.
     * @type {string}
     * @memberof NetworkPropertiesDTO
     */
    epochAdjustment?: string;
}
/**
 * Check if a given object implements the NetworkPropertiesDTO interface.
 */
export declare function instanceOfNetworkPropertiesDTO(value: object): boolean;
export declare function NetworkPropertiesDTOFromJSON(json: any): NetworkPropertiesDTO;
export declare function NetworkPropertiesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkPropertiesDTO;
export declare function NetworkPropertiesDTOToJSON(value?: NetworkPropertiesDTO | null): any;
