/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainPropertiesDTOFromJSON, ChainPropertiesDTOToJSON, } from './ChainPropertiesDTO';
import { NetworkPropertiesDTOFromJSON, NetworkPropertiesDTOToJSON, } from './NetworkPropertiesDTO';
import { PluginsPropertiesDTOFromJSON, PluginsPropertiesDTOToJSON, } from './PluginsPropertiesDTO';
/**
 * Check if a given object implements the NetworkConfigurationDTO interface.
 */
export function instanceOfNetworkConfigurationDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'network' in value;
    isInstance = isInstance && 'chain' in value;
    isInstance = isInstance && 'plugins' in value;
    return isInstance;
}
export function NetworkConfigurationDTOFromJSON(json) {
    return NetworkConfigurationDTOFromJSONTyped(json, false);
}
export function NetworkConfigurationDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network: NetworkPropertiesDTOFromJSON(json['network']),
        chain: ChainPropertiesDTOFromJSON(json['chain']),
        plugins: PluginsPropertiesDTOFromJSON(json['plugins']),
    };
}
export function NetworkConfigurationDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network: NetworkPropertiesDTOToJSON(value.network),
        chain: ChainPropertiesDTOToJSON(value.chain),
        plugins: PluginsPropertiesDTOToJSON(value.plugins),
    };
}
