/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodeHealthDTOFromJSON, NodeHealthDTOToJSON } from './NodeHealthDTO';
/**
 * Check if a given object implements the NodeHealthInfoDTO interface.
 */
export function instanceOfNodeHealthInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'status' in value;
    return isInstance;
}
export function NodeHealthInfoDTOFromJSON(json) {
    return NodeHealthInfoDTOFromJSONTyped(json, false);
}
export function NodeHealthInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        status: NodeHealthDTOFromJSON(json['status']),
    };
}
export function NodeHealthInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        status: NodeHealthDTOToJSON(value.status),
    };
}
