/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export var NodeStatusEnum = {
    Up: 'up',
    Down: 'down',
};
export function NodeStatusEnumFromJSON(json) {
    return NodeStatusEnumFromJSONTyped(json, false);
}
export function NodeStatusEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function NodeStatusEnumToJSON(value) {
    return value;
}
