/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Indicates how to sort the results:
 * * ``asc`` - ascending
 * * ``desc`` - descending
 * @export
 */
export var Order = {
    Asc: 'asc',
    Desc: 'desc',
};
export function OrderFromJSON(json) {
    return OrderFromJSONTyped(json, false);
}
export function OrderFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function OrderToJSON(value) {
    return value;
}
