/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ParentPublicKeySignaturePair interface.
 */
export function instanceOfParentPublicKeySignaturePair(value) {
    var isInstance = true;
    isInstance = isInstance && 'parentPublicKey' in value;
    isInstance = isInstance && 'signature' in value;
    return isInstance;
}
export function ParentPublicKeySignaturePairFromJSON(json) {
    return ParentPublicKeySignaturePairFromJSONTyped(json, false);
}
export function ParentPublicKeySignaturePairFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        parentPublicKey: json['parentPublicKey'],
        signature: json['signature'],
    };
}
export function ParentPublicKeySignaturePairToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        parentPublicKey: value.parentPublicKey,
        signature: value.signature,
    };
}
