/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the RentalFeesDTO interface.
 */
export function instanceOfRentalFeesDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'effectiveRootNamespaceRentalFeePerBlock' in value;
    isInstance = isInstance && 'effectiveChildNamespaceRentalFee' in value;
    isInstance = isInstance && 'effectiveMosaicRentalFee' in value;
    return isInstance;
}
export function RentalFeesDTOFromJSON(json) {
    return RentalFeesDTOFromJSONTyped(json, false);
}
export function RentalFeesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        effectiveRootNamespaceRentalFeePerBlock: json['effectiveRootNamespaceRentalFeePerBlock'],
        effectiveChildNamespaceRentalFee: json['effectiveChildNamespaceRentalFee'],
        effectiveMosaicRentalFee: json['effectiveMosaicRentalFee'],
    };
}
export function RentalFeesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        effectiveRootNamespaceRentalFeePerBlock: value.effectiveRootNamespaceRentalFeePerBlock,
        effectiveChildNamespaceRentalFee: value.effectiveChildNamespaceRentalFee,
        effectiveMosaicRentalFee: value.effectiveMosaicRentalFee,
    };
}
