/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ResolutionEntryDTOResolved } from './ResolutionEntryDTOResolved';
import type { SourceDTO } from './SourceDTO';
/**
 *
 * @export
 * @interface ResolutionEntryDTO
 */
export interface ResolutionEntryDTO {
    /**
     *
     * @type {SourceDTO}
     * @memberof ResolutionEntryDTO
     */
    source: SourceDTO;
    /**
     *
     * @type {ResolutionEntryDTOResolved}
     * @memberof ResolutionEntryDTO
     */
    resolved: ResolutionEntryDTOResolved;
}
/**
 * Check if a given object implements the ResolutionEntryDTO interface.
 */
export declare function instanceOfResolutionEntryDTO(value: object): boolean;
export declare function ResolutionEntryDTOFromJSON(json: any): ResolutionEntryDTO;
export declare function ResolutionEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolutionEntryDTO;
export declare function ResolutionEntryDTOToJSON(value?: ResolutionEntryDTO | null): any;
