/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the SecretLockNetworkPropertiesDTO interface.
 */
export function instanceOfSecretLockNetworkPropertiesDTO(value) {
    var isInstance = true;
    return isInstance;
}
export function SecretLockNetworkPropertiesDTOFromJSON(json) {
    return SecretLockNetworkPropertiesDTOFromJSONTyped(json, false);
}
export function SecretLockNetworkPropertiesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        maxSecretLockDuration: !exists(json, 'maxSecretLockDuration') ? undefined : json['maxSecretLockDuration'],
        minProofSize: !exists(json, 'minProofSize') ? undefined : json['minProofSize'],
        maxProofSize: !exists(json, 'maxProofSize') ? undefined : json['maxProofSize'],
    };
}
export function SecretLockNetworkPropertiesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        maxSecretLockDuration: value.maxSecretLockDuration,
        minProofSize: value.minProofSize,
        maxProofSize: value.maxProofSize,
    };
}
