/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerDTOFromJSON, ServerDTOToJSON } from './ServerDTO';
/**
 * Check if a given object implements the ServerInfoDTO interface.
 */
export function instanceOfServerInfoDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'serverInfo' in value;
    return isInstance;
}
export function ServerInfoDTOFromJSON(json) {
    return ServerInfoDTOFromJSONTyped(json, false);
}
export function ServerInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        serverInfo: ServerDTOFromJSON(json['serverInfo']),
    };
}
export function ServerInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        serverInfo: ServerDTOToJSON(value.serverInfo),
    };
}
