/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DeploymentDTO } from './DeploymentDTO';
/**
 *
 * @export
 * @interface ServerDTO
 */
export interface ServerDTO {
    /**
     * catapult-rest component version.
     * @type {string}
     * @memberof ServerDTO
     */
    restVersion: string;
    /**
     * catapult-sdk component version.
     * @type {string}
     * @memberof ServerDTO
     */
    sdkVersion: string;
    /**
     *
     * @type {DeploymentDTO}
     * @memberof ServerDTO
     */
    deployment: DeploymentDTO;
}
/**
 * Check if a given object implements the ServerDTO interface.
 */
export declare function instanceOfServerDTO(value: object): boolean;
export declare function ServerDTOFromJSON(json: any): ServerDTO;
export declare function ServerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerDTO;
export declare function ServerDTOToJSON(value?: ServerDTO | null): any;
