/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ServerDTO } from './ServerDTO';
/**
 *
 * @export
 * @interface ServerInfoDTO
 */
export interface ServerInfoDTO {
    /**
     *
     * @type {ServerDTO}
     * @memberof ServerInfoDTO
     */
    serverInfo: ServerDTO;
}
/**
 * Check if a given object implements the ServerInfoDTO interface.
 */
export declare function instanceOfServerInfoDTO(value: object): boolean;
export declare function ServerInfoDTOFromJSON(json: any): ServerInfoDTO;
export declare function ServerInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfoDTO;
export declare function ServerInfoDTOToJSON(value?: ServerInfoDTO | null): any;
