/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the TransactionMetaDTO interface.
 */
export function instanceOfTransactionMetaDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'height' in value;
    isInstance = isInstance && 'hash' in value;
    isInstance = isInstance && 'merkleComponentHash' in value;
    isInstance = isInstance && 'index' in value;
    return isInstance;
}
export function TransactionMetaDTOFromJSON(json) {
    return TransactionMetaDTOFromJSONTyped(json, false);
}
export function TransactionMetaDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        height: json['height'],
        hash: json['hash'],
        merkleComponentHash: json['merkleComponentHash'],
        index: json['index'],
        timestamp: !exists(json, 'timestamp') ? undefined : json['timestamp'],
        feeMultiplier: !exists(json, 'feeMultiplier') ? undefined : json['feeMultiplier'],
    };
}
export function TransactionMetaDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        height: value.height,
        hash: value.hash,
        merkleComponentHash: value.merkleComponentHash,
        index: value.index,
        timestamp: value.timestamp,
        feeMultiplier: value.feeMultiplier,
    };
}
