/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TransactionInfoDTOMeta
 */
export interface TransactionInfoDTOMeta {
    /**
     * Height of the blockchain.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    height: string;
    /**
     *
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    hash: string;
    /**
     *
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    merkleComponentHash: string;
    /**
     * Transaction index within the aggregate.
     * @type {number}
     * @memberof TransactionInfoDTOMeta
     */
    index: number;
    /**
     * Number of milliseconds elapsed since the creation of the nemesis block. This value can be converted to epoch time by adding the network's 'epochAdjustment'.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    timestamp?: string;
    /**
     * Fee multiplier applied to transactions contained in block.
     * @type {number}
     * @memberof TransactionInfoDTOMeta
     */
    feeMultiplier?: number;
    /**
     *
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    aggregateHash: string;
    /**
     * Identifier of the aggregate transaction.
     * @type {string}
     * @memberof TransactionInfoDTOMeta
     */
    aggregateId: string;
}
/**
 * Check if a given object implements the TransactionInfoDTOMeta interface.
 */
export declare function instanceOfTransactionInfoDTOMeta(value: object): boolean;
export declare function TransactionInfoDTOMetaFromJSON(json: any): TransactionInfoDTOMeta;
export declare function TransactionInfoDTOMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInfoDTOMeta;
export declare function TransactionInfoDTOMetaToJSON(value?: TransactionInfoDTOMeta | null): any;
