/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the TransactionIds interface.
 */
export function instanceOfTransactionIds(value) {
    var isInstance = true;
    return isInstance;
}
export function TransactionIdsFromJSON(json) {
    return TransactionIdsFromJSONTyped(json, false);
}
export function TransactionIdsFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        transactionIds: !exists(json, 'transactionIds') ? undefined : json['transactionIds'],
    };
}
export function TransactionIdsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        transactionIds: value.transactionIds,
    };
}
