/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Pagination } from './Pagination';
import type { TransactionInfoDTO } from './TransactionInfoDTO';
/**
 *
 * @export
 * @interface TransactionPage
 */
export interface TransactionPage {
    /**
     * Array of transactions.
     * @type {Array<TransactionInfoDTO>}
     * @memberof TransactionPage
     */
    data: Array<TransactionInfoDTO>;
    /**
     *
     * @type {Pagination}
     * @memberof TransactionPage
     */
    pagination: Pagination;
}
/**
 * Check if a given object implements the TransactionPage interface.
 */
export declare function instanceOfTransactionPage(value: object): boolean;
export declare function TransactionPageFromJSON(json: any): TransactionPage;
export declare function TransactionPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPage;
export declare function TransactionPageToJSON(value?: TransactionPage | null): any;
