/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TransactionFeesDTO interface.
 */
export function instanceOfTransactionFeesDTO(value) {
    var isInstance = true;
    isInstance = isInstance && 'averageFeeMultiplier' in value;
    isInstance = isInstance && 'medianFeeMultiplier' in value;
    isInstance = isInstance && 'highestFeeMultiplier' in value;
    isInstance = isInstance && 'lowestFeeMultiplier' in value;
    isInstance = isInstance && 'minFeeMultiplier' in value;
    return isInstance;
}
export function TransactionFeesDTOFromJSON(json) {
    return TransactionFeesDTOFromJSONTyped(json, false);
}
export function TransactionFeesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        averageFeeMultiplier: json['averageFeeMultiplier'],
        medianFeeMultiplier: json['medianFeeMultiplier'],
        highestFeeMultiplier: json['highestFeeMultiplier'],
        lowestFeeMultiplier: json['lowestFeeMultiplier'],
        minFeeMultiplier: json['minFeeMultiplier'],
    };
}
export function TransactionFeesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        averageFeeMultiplier: value.averageFeeMultiplier,
        medianFeeMultiplier: value.medianFeeMultiplier,
        highestFeeMultiplier: value.highestFeeMultiplier,
        lowestFeeMultiplier: value.lowestFeeMultiplier,
        minFeeMultiplier: value.minFeeMultiplier,
    };
}
