/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UnlockedAccountDTO
 */
export interface UnlockedAccountDTO {
    /**
     *
     * @type {Array<string>}
     * @memberof UnlockedAccountDTO
     */
    unlockedAccount: Array<string>;
}
/**
 * Check if a given object implements the UnlockedAccountDTO interface.
 */
export declare function instanceOfUnlockedAccountDTO(value: object): boolean;
export declare function UnlockedAccountDTOFromJSON(json: any): UnlockedAccountDTO;
export declare function UnlockedAccountDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlockedAccountDTO;
export declare function UnlockedAccountDTOToJSON(value?: UnlockedAccountDTO | null): any;
