/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageNationFromJSON, PageNationToJSON } from './PageNation';
import { UserFromJSON, UserToJSON } from './User';
/**
 * Check if a given object implements the GetUsersResponseInner interface.
 */
export function instanceOfGetUsersResponseInner(value) {
    var isInstance = true;
    isInstance = isInstance && 'pageNation' in value;
    isInstance = isInstance && 'data' in value;
    return isInstance;
}
export function GetUsersResponseInnerFromJSON(json) {
    return GetUsersResponseInnerFromJSONTyped(json, false);
}
export function GetUsersResponseInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        pageNation: PageNationFromJSON(json['pageNation']),
        data: json['data'].map(UserFromJSON),
    };
}
export function GetUsersResponseInnerToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        pageNation: PageNationToJSON(value.pageNation),
        data: value.data.map(UserToJSON),
    };
}
