/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the PageNation interface.
 */
export function instanceOfPageNation(value) {
    var isInstance = true;
    isInstance = isInstance && 'total' in value;
    isInstance = isInstance && 'current' in value;
    isInstance = isInstance && 'last' in value;
    return isInstance;
}
export function PageNationFromJSON(json) {
    return PageNationFromJSONTyped(json, false);
}
export function PageNationFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        total: json['total'],
        current: json['current'],
        last: json['last'],
    };
}
export function PageNationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        total: value.total,
        current: value.current,
        last: value.last,
    };
}
