/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PageNation
 */
export interface PageNation {
    /**
     *
     * @type {number}
     * @memberof PageNation
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof PageNation
     */
    current: number;
    /**
     *
     * @type {number}
     * @memberof PageNation
     */
    last: number;
}
/**
 * Check if a given object implements the PageNation interface.
 */
export declare function instanceOfPageNation(value: object): boolean;
export declare function PageNationFromJSON(json: any): PageNation;
export declare function PageNationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageNation;
export declare function PageNationToJSON(value?: PageNation | null): any;
