/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the PostChatRoomToMessageBody interface.
 */
export function instanceOfPostChatRoomToMessageBody(value) {
    var isInstance = true;
    isInstance = isInstance && 'message' in value;
    return isInstance;
}
export function PostChatRoomToMessageBodyFromJSON(json) {
    return PostChatRoomToMessageBodyFromJSONTyped(json, false);
}
export function PostChatRoomToMessageBodyFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        message: json['message'],
    };
}
export function PostChatRoomToMessageBodyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        message: value.message,
    };
}
