/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RewardFromJSON, RewardToJSON } from './Reward';
/**
 * Check if a given object implements the QuestUpdateRequest interface.
 */
export function instanceOfQuestUpdateRequest(value) {
    var isInstance = true;
    isInstance = isInstance && 'title' in value;
    isInstance = isInstance && 'description' in value;
    isInstance = isInstance && 'deadline' in value;
    isInstance = isInstance && 'reward' in value;
    return isInstance;
}
export function QuestUpdateRequestFromJSON(json) {
    return QuestUpdateRequestFromJSONTyped(json, false);
}
export function QuestUpdateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        title: json['title'],
        description: json['description'],
        deadline: new Date(json['deadline']),
        reward: RewardFromJSON(json['reward']),
    };
}
export function QuestUpdateRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        title: value.title,
        description: value.description,
        deadline: value.deadline.toISOString(),
        reward: RewardToJSON(value.reward),
    };
}
