/* tslint:disable */
/* eslint-disable */
/**
 * Decentralized-Guild
 * About Decentralized Guild System APIs. Please use it when expanding the system.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export var QuestWorkerStatusEnum = {
    Applying: 'APPLYING',
    Accepted: 'ACCEPTED',
    Completed: 'COMPLETED',
    Rejected: 'REJECTED',
};
export function QuestWorkerStatusEnumFromJSON(json) {
    return QuestWorkerStatusEnumFromJSONTyped(json, false);
}
export function QuestWorkerStatusEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function QuestWorkerStatusEnumToJSON(value) {
    return value;
}
