import Link from '@/components/atom/Link';
import MarkdownParser from '@/components/atom/MarkdownParser';
import Template from '@/components/templates/Template';
import paths from '@/services/Navigaion';
import Container from '@mui/material/Container';
import { useSession } from 'next-auth/react';

export default function PrivacyPolicy(): JSX.Element {
  const { data: session } = useSession();

  return (
    <Template>
      <Container maxWidth={'md'} style={{ marginTop: '5rem', marginBottom: '5rem' }}>
        <Link
          href={session ? paths.quest.dashboard.href : paths.root.index.href}
          style={{ textAlign: 'right', display: 'block' }}
        >
          HOME
        </Link>
        <div style={{ marginTop: '2rem', marginBottom: '2rem' }}>
          <MarkdownParser markdownText={TEXT} />
        </div>
        <Link
          href={session ? paths.quest.dashboard.href : paths.root.index.href}
          style={{ textAlign: 'right', display: 'block' }}
        >
          HOME
        </Link>
      </Container>
    </Template>
  );
}

const TEXT = `
# Decentralized Guild Privacy Policy

#### Information we obtain from you
This application acquires the following information from customers.
- Full name (including nicknames and pen names)
- Age or date of birth
- sex
- Occupation, work history, educational background
- mail address
- telephone number
- Information about your payment method such as credit card, bank account, electronic money, etc.
- ID used by the customer in the external service, and other information that the customer has permitted to disclose to the partner through the privacy settings of the external service
- Identification information generated using cookies
- Information related to the OS and devices used by the customer, such as the ID generated by the OS, the type of device, and the device identifier
- Customer behavior history on this app website, such as time spent on this app website, input history, purchase history, etc.
- Usage history of this application such as startup time of this application, input history, purchase history

#### Purposes for which we use your information
This application uses the information obtained from customers for the following purposes.
- To accept registration for this application service, verify the identity of the customer, and authenticate
- To manage the customer's usage history of this application service
- For settlement of usage fees
- To analyze the customer's behavior history in this application service and use it for maintenance and improvement of this application service
- To provide information regarding the services of this app
- To respond to customer inquiries
- To respond to acts that violate the terms of this app or laws and regulations
- To notify you of changes, discontinuation of provision, termination, and contract termination of this application service
- To notify you of changes, etc. to the Terms of the App
- In addition to the above, to provide, maintain, protect and improve this application service

#### Measures taken for safety management
If you contact us at the contact information listed at the end of this application, we will respond individually in accordance with the provisions of laws and regulations regarding the measures taken for the safety management of information acquired from customers by this application.

#### Provided by Third Parties
Of the information obtained from customers, this application may, without prior consent of the customer, handle personal data (Article 16, Paragraph 3 of the Act on the Protection of Personal Information), ) will not be provided.
However, the following cases are excluded.
- When outsourcing the handling of personal data
- If this app service is acquired
- When joint use is made with business partners (If there is a specific joint use, the details will be announced separately.)
- Other cases where provision to a third party is legally permitted by law

#### Access Analysis Tool
This app uses "Google Analytics" for customer access analysis. Google Analytics uses cookies to collect traffic data. Traffic data is collected anonymously and is not personally identifiable. You can refuse to collect this information by disabling cookies. Please check your browser settings for details. For more information about Google Analytics, please see below.

[https://marketingplatform.google.com/about/analytics/terms/en/](https://marketingplatform.google.com/about/analytics/terms/en/)

#### Changes to the Privacy Policy
This app will change the contents of this privacy policy as necessary. In this case, we will inform or notify the time and content of the revised privacy policy in an appropriate manner.

#### Inquiry
If you wish to disclose, correct, stop using, or delete your information, please contact us at the email address below.

email: ym.u.ichiro@gmail.com

#### Business Name
Decentralized Guild

Established on August 6, 2023
`;

const TEXT_JP = `
# Decentralized Guild プライバシーポリシー

#### お客様から取得する情報
当アプリは、お客様から以下の情報を取得します。
- 氏名(ニックネームやペンネームも含む)
- 年齢または生年月日
- 性別
- 職業、職歴、学歴
- メールアドレス
- 電話番号
- クレジットカード、銀行口座、電子マネー等のお客様の決済手段に関する情報
- 外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報
- Cookie(クッキー)を用いて生成された識別情報
- OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報
- 当アプリウェブサイトの滞在時間、入力履歴、購買履歴等の当アプリウェブサイトにおけるお客様の行動履歴
- 当アプリアプリの起動時間、入力履歴、購買履歴等の当アプリアプリの利用履歴

#### お客様の情報を利用する目的
当アプリは、お客様から取得した情報を、以下の目的のために利用します。
- 当アプリサービスに関する登録の受付、お客様の本人確認、認証のため
- お客様の当アプリサービスの利用履歴を管理するため
- 利用料金の決済のため
- 当アプリサービスにおけるお客様の行動履歴を分析し、当アプリサービスの維持改善に役立てるため
- 当アプリのサービスに関するご案内をするため
- お客様からのお問い合わせに対応するため
- 当アプリの規約や法令に違反する行為に対応するため
- 当アプリサービスの変更、提供中止、終了、契約解除をご連絡するため
- 当アプリ規約の変更等を通知するため
- 以上の他、当アプリサービスの提供、維持、保護及び改善のため

#### 安全管理のために講じた措置
当アプリが、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。

#### 第三者提供
当アプリは、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
但し、次の場合は除きます。
- 個人データの取扱いを外部に委託する場合
- 当アプリサービスが買収された場合
- 事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）
- その他、法律によって合法的に第三者提供が許されている場合

#### アクセス解析ツール
当アプリは、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。
https://marketingplatform.google.com/about/analytics/terms/jp/

#### プライバシーポリシーの変更
当アプリは、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。

#### お問い合わせ
お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のメールアドレスにご連絡ください。

e-mail
ym.u.ichiro@gmail.com

#### 事業者の氏名
Decentralized Guild

2023年08月06日 制定

`;
